language: node_js
node_js:
  - "7"
  
sudo: required
services:
  - docker

before_install:
  - docker build -t gabopersa/docker-react -f Dockerfile.dev .

script-install:
  - docker run gabopersa/docker-react npm run test -- --coverage

